apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: mki-provisioning-base
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.upbound.io/upbound/provider-kubernetes
    version: "v0.18.0"
